|        | GET|HEAD  | maintenance/membershiptype                       | membershiptype.index     | App\Http\Controllers\MembershipTypeController@index                    | web          |
|        | POST      | maintenance/membershiptype                       | membershiptype.store     | App\Http\Controllers\MembershipTypeController@store                    | web          |
|        | GET|HEAD  | maintenance/membershiptype/create                | membershiptype.create    | App\Http\Controllers\MembershipTypeController@create                   | web          |
|        | GET|HEAD  | maintenance/membershiptype/printall/{order}      | membershiptype.printall  | App\Http\Controllers\MembershipTypeController@printAll                 | web          |
|        | GET|HEAD  | maintenance/membershiptype/setsearch             | membershiptype.setSearch | App\Http\Controllers\MembershipTypeController@setSearch                | web          |
|        | GET|HEAD  | maintenance/membershiptype/sortorder/{order}     | membershiptype.sortorder | App\Http\Controllers\MembershipTypeController@setSortOrder             | web          |
|        | GET|HEAD  | maintenance/membershiptype/{membershiptype}      | membershiptype.show      | App\Http\Controllers\MembershipTypeController@show                     | web          |
|        | DELETE    | maintenance/membershiptype/{membershiptype}      | membershiptype.destroy   | App\Http\Controllers\MembershipTypeController@destroy                  | web          |
|        | PUT|PATCH | maintenance/membershiptype/{membershiptype}      | membershiptype.update    | App\Http\Controllers\MembershipTypeController@update                   | web          |
|        | GET|HEAD  | maintenance/membershiptype/{membershiptype}/edit | membershiptype.edit      | App\Http\Controllers\MembershipTypeController@edit                     | web          |
|        | GET|HEAD  | maintenance/phonetype                            | phonetype.index          | App\Http\Controllers\PhoneTypeController@index                         | web          |
|        | POST      | maintenance/phonetype                            | phonetype.store          | App\Http\Controllers\PhoneTypeController@store                         | web          |
|        | GET|HEAD  | maintenance/phonetype/create                     | phonetype.create         | App\Http\Controllers\PhoneTypeController@create                        | web          |
|        | GET|HEAD  | maintenance/phonetype/printall/{order}           | phonetype.printall       | App\Http\Controllers\PhoneTypeController@printAll                      | web          |
|        | GET|HEAD  | maintenance/phonetype/setsearch                  | phonetype.setSearch      | App\Http\Controllers\PhoneTypeController@setSearch                     | web          |
|        | GET|HEAD  | maintenance/phonetype/sortorder/{order}          | phonetype.sortorder      | App\Http\Controllers\PhoneTypeController@setSortOrder                  | web          |
|        | GET|HEAD  | maintenance/phonetype/{phonetype}                | phonetype.show           | App\Http\Controllers\PhoneTypeController@show                          | web          |
|        | DELETE    | maintenance/phonetype/{phonetype}                | phonetype.destroy        | App\Http\Controllers\PhoneTypeController@destroy                       | web          |
|        | PUT|PATCH | maintenance/phonetype/{phonetype}                | phonetype.update         | App\Http\Controllers\PhoneTypeController@update                        | web          |
|        | GET|HEAD  | maintenance/phonetype/{phonetype}/edit           | phonetype.edit           | App\Http\Controllers\PhoneTypeController@edit                          | web          |
